/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    PerformanceMonitor: typeof import('./src/components/PerformanceMonitor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./src/components/SectionTitle.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    ThreeScene: typeof import('./src/components/ThreeScene.vue')['default']
  }
}
